
AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'spec/dummy/**/*'

Metrics/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: false
